language: python

python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
        libfftw3-dev

branches:
  only:
    - master
    - travis_fix

before_install:
  - sudo apt-get update
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch -c pytorch
  - source activate test-environment
  - python setup.py build_ext --inplace

script:
  - python -m unittest discover -s test/

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 flake8-print
      script: flake8
